// Course fetching
export const FETCH_COURSES_REQUEST = 'FETCH_COURSES_REQUEST';
export const FETCH_COURSES_SUCCESS = 'FETCH_COURSES_SUCCESS';
export const FETCH_COURSES_FAILURE = 'FETCH_COURSES_FAILURE';

// Course details
export const FETCH_COURSE_DETAILS_REQUEST = 'FETCH_COURSE_DETAILS_REQUEST';
export const FETCH_COURSE_DETAILS_SUCCESS = 'FETCH_COURSE_DETAILS_SUCCESS';
export const FETCH_COURSE_DETAILS_FAILURE = 'FETCH_COURSE_DETAILS_FAILURE';

// Enrollment
export const ENROLL_IN_COURSE = 'ENROLL_IN_COURSE';
export const MARK_COURSE_AS_COMPLETED = 'MARK_COURSE_AS_COMPLETED';

// Real-time updates
export const UPDATE_COURSE_LIKES = 'UPDATE_COURSE_LIKES';